### ISSUE TITLE
Correlation value is 'nan' for single chromosome 

### ISSUE THREAD

**Issue by mdahasan** [favorov/stereogene#1]
I have bed files representing peak at different time points. While I run _Stereogene_ genome wide, it worked, however, when I tried to run the tool on individual chromosome the correlation is always showing value 'nan'. Could you tell me what might be the problem and how to counter this problem?

Also, the default window size are fixed at 10,000. How can I change this parameter. It is said in the manual that I can change into the config file. Is it that I make a config file with desired parameter and pass the config file as an argument?

**Comment by favorov** [comment]
Thank you. We will test the 1-chromosome story. The window sizes can be changed either by command-line switch -wSize=N or by  wSize=N line in config file, the file is referred by -cfg=cfgfilename. Please refer to StereoGene_read_me.doc for details.

**Comment by favorov** [comment]
Dear Dr Hasan,

Thank you for using our tool.

About your questions:
1. The program do not have a special option for single chromosome analysis. But the program can output the results by chromosomes. To do this you can use switch outChrom=1. The file *.dist will give you a table that will contain cross-correlation functions by chromosomes. The file *.fg contains the correlation coefficient by windows with chromosomes and positions.Using simple r-script you can select the chromosome of interest. But the background distribution will be given relative to the entire genome.
2. About the window size and other parameters. You have different ways to define the parameters. You can use a traditional method for the parameters definition -- use a command line. To redefine the parameter value you should add to the command line new parameter value like wSize=500000. Because the program has rather large amount of the parameters you can simplify the command line and you can redefine all the parameters you need in a special config file and refer to the config file in the command line.

We do not recommend to use a short window size. This value gives very wide distributions. If you are interesting in positions on the genome where there exists a high correlation you can use an option outWig=BASE. In this case you will obtain a wig-file with a local correlations.

We released 1.66 improving the diagnostics.
