### ISSUE TITLE
unknown parameter gene_beg

### ISSUE THREAD

**Issue by pastaxingxin** [favorov/stereogene#5]
Hi,

When I ran "./StereoGene cfg=sg.cfg  genes_refSeq.bed b_g.H3K4me3.wig -gene_beg maxZero=100 maxNA=100" in the example.sh,

I got "unknown parameter gene_beg". It couldn't work at all...How to resolve the issue?

**Comment by favorov** [comment]
Thank you, I'll try to reproduce the issue.

**Comment by favorov** [comment]
The -gene_beg was obsoleted in version 2.10 (src/version_history.txt) -- looks like the example.sh you use is from an old version.
Instead of -gene_beg switch , please use parse_genes program (it is in the same package) that created a lot of annotations, particularly, gene starts, from an annotation bed file.
